name: Build Hugo
on:
  workflow_dispatch: 

jobs: 
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - run: bash build.sh
      env:
        SSH_KEY: ${{ secrets.DH_KEY }}
        DEST_OS: ${{ matrix.os }}

  upx:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: bash upx.sh
      env:
        SSH_KEY: ${{ secrets.DH_KEY }}
        DEST_OS: ${{ matrix.os }}
