name: Build Binaries
on:
  workflow_dispatch: 

jobs: 
  build:
    strategy:
      fail-fast: false
      matrix:
#         os: [macos, ubuntu]
        os: [macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Binary
      id: binary
      run: bash build.sh
      env:
        SSH_KEY: ${{ secrets.DH_KEY }}
