name: Python
on: [workflow_dispatch]
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "action_state=yellow" >> $GITHUB_ENV
        echo "action_state=red" >> $GITHUB_ENV
        echo "foo=bar" >> $GITHUB_ENV

  build:
    needs: [test]
    strategy:
#       fail-fast: false
      matrix:
#        os: [macos, ubuntu, windows]
        os: [windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with: {python-version: '3.8'}
    - name: Install and test
      env:
       GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo $action_state
        echo $foo
        bash .github/scripts/build.sh
