name: Python
on: [workflow_dispatch]
defaults:
  run: { shell: bash }

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ toJson(steps) }}
    steps:
    - id: step1
      env:
       GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "::set-output name=action_fruit::strawberry"

  build:
    needs: [prebuild]
    strategy:
      fail-fast: false
      matrix: { os: [macos, ubuntu, windows] }
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with: {python-version: '3.8'}
    - name: Install and test
      env:
       GITHUB_NEEDS: ${{ toJson(needs) }}
       GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        pip install -Uq ghapi
        bash .github/scripts/build.sh
