name: Python
on: [workflow_dispatch]
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: |
        echo "::set-output name=action_fruit::strawberry"
        echo "action_state=yellow" >> $GITHUB_ENV
        echo "action_state=red" >> $GITHUB_ENV
        echo "foo=bar" >> $GITHUB_ENV

  build:
    needs: [test]
#     strategy:
#       fail-fast: false
#       matrix:
#        os: [macos, ubuntu, windows]
#         os: [windows]
#     runs-on: ${{ matrix.os }}-latest
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v1
#     - uses: actions/setup-python@v2
#       with: {python-version: '3.8'}
    - name: Install and test
      env:
       GITHUB_JOBS: ${{ toJson(needs) }}
#        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo $GITHUB_JOBS
#         bash .github/scripts/build.sh
