name: Test
on:
  workflow_dispatch: 

jobs: 
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build hugo
      run: |
        pip install fastcore
        python build.py
    - uses: actions/upload-artifact@v2
      with:
        name: hugo-windows
        path: hugo/hugo.exe
