name: Test
on:
  workflow_dispatch: 

jobs: 
  build:
    runs-on: windows-latest
    steps:
    - run: |
        go version
        patch --version
        diff --version
#     - uses: actions/checkout@v2
