name: Windows
defaults:
  run:
    shell: powershell
on:
  workflow_dispatch: 

jobs: 
  build:
    runs-on: windows-latest
    steps:
    - uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 16GB
        disk-root: "C:"
    - run: (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
    - run: |
        Get-PSDrive
        cinst --no-progress openssh
        scp
        pip install fastcore
