name: Windows
defaults:
  run:
    shell: powershell
on:
  workflow_dispatch: 

jobs: 
  build:
    runs-on: windows-latest
    steps:
    - run: (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
    - uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 16GB
        disk-root: "C:"
    - run: Get-PSDrive
    - uses: actions/checkout@v2
    - run: cinst --no-progress openssh rsync
    - run: rsync
#         scp
#         pip install fastcore
#         python build.py
